
spring.application.name=backend

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ecommercedb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:0110}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#desactivar auto-configuradores de usuario y password
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

#Paypal sandbox
paypal.mode=${PAYPAL_MODE:sandbox}
paypal.client.id=${PAYPAL_CLIENT_ID:}
paypal.client.secret=${PAYPAL_CLIENT_SECRET:}
